project:
  type: website

website:
  title: "Veles Documentation"
  favicon: ./figs/Veles-rune-gray.svg
  navbar:
    logo: ./figs/Veles-rune-gray.png
    pinned: true
    right:
      - text: "{{< fa flask >}} VelesWeb"
        href: https://www.velesweb.org/
      - text: " "
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/jakub-jedrusiak/VelesResearch
          - text: Issues
            url: https://github.com/jakub-jedrusiak/VelesResearch/issues
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Getting started"
        href: getting-started.qmd
      - text: "Reference"
        contents: "ref/**"
    collapse-level: 3
  twitter-card: true
  open-graph: true
  repo-url: https://github.com/jakub-jedrusiak/VelesDocs
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    css: ./styles/styles.css
    toc: true
resources:
  - CNAME
