project:
  type: website

website:
  title: "Veles Documentation"
  favicon: ./figs/Veles-rune-gray.svg
  navbar:
    logo: ./figs/Veles-rune-gray.png
    pinned: true
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/jakub-jedrusiak/mtscr
          - text: Issues
            url: https://github.com/jakub-jedrusiak/mtscr/issues
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Getting started"
        href: getting-started.qmd
      - text: "Reference"
        contents: "ref/**"
  twitter-card: true
  open-graph: true
  repo-url: https://github.com/jakub-jedrusiak/veles-docs
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    css: ./styles/styles.css
    toc: true
