project:
  type: website

website:
  title: "Veles Documentation"
  site-url: "https://docs.velesweb.org/"
  favicon: ./figs/Veles-rune-gray.svg
  navbar:
    logo: ./figs/Veles-rune-gray.png
    pinned: true
    right:
      - text: "{{< fa flask >}} VelesWeb"
        href: https://www.velesweb.org/
      - text: " "
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/jakub-jedrusiak/VelesResearch
          - text: Issues
            url: https://github.com/jakub-jedrusiak/VelesResearch/issues
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Getting started"
        href: getting-started.qmd
      - section: "Library"
        contents:
          - library/overview.qmd
          - library/en.qmd
          - section: "Other languages"
            contents: "library/languages/*"
      - section: "Reference"
        contents: "ref/**"
      - text: "<script type='text/javascript' src='https://storage.ko-fi.com/cdn/widget/Widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Support Me on Ko-fi', '#2C3E50', 'C0C6MPH76');kofiwidget2.draw();</script> "
    collapse-level: 2
  twitter-card: true
  open-graph: true
  repo-url: https://github.com/jakub-jedrusiak/VelesDocs
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    css: ./styles/styles.css
    toc: true
resources:
  - CNAME
