project:
  type: website

website:
  title: "Veles Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Getting Started
  twitter-card: true
  open-graph: true
  repo-url: https://github.com/jakub-jedrusiak/veles-docs
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    css: ./styles/styles.css
    toc: true
