project:
  type: website

website:
  title: "Veles Documentation"
  favicon: ./figs/Veles-rune-gray.svg
  navbar:
    logo: ./figs/Veles-rune-gray.png
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Basics"
        contents:
          - text: "Getting started"
            href: getting-started.qmd
  twitter-card: true
  open-graph: true
  repo-url: https://github.com/jakub-jedrusiak/veles-docs
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: [flatly, ./styles/light.scss]
      dark: [darkly, ./styles/dark.scss]
    css: ./styles/styles.css
    toc: true
